/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Livro;
import repositorio.RepositorioLivro;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author gabrielaambos
 */
public class TelaAdicionarLivro extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private Livro livro;
    public TelaAdicionarLivro(Livro livro) {
        initComponents();
        this.livro = livro;
        if(livro != null) {
            recebeLivro();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id_grupoTem = new javax.swing.ButtonGroup();
        id_botaoSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        id_titulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        id_ano = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        id_editora = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        id_autor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        id_edicao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        id_serie = new javax.swing.JTextField();
        id_tem = new javax.swing.JRadioButton();
        id_quer = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        id_botaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        id_botaoSalvar.setText("Salvar");
        id_botaoSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id_botaoSalvarMouseClicked(evt);
            }
        });

        jLabel1.setText("Título");

        jLabel2.setText("Ano");

        id_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_anoActionPerformed(evt);
            }
        });

        jLabel3.setText("Editora");

        jLabel4.setText("Autor");

        jLabel5.setText("Edição");

        jLabel6.setText("Série");

        id_grupoTem.add(id_tem);
        id_tem.setSelected(true);
        id_tem.setText("Tem na estante");

        id_grupoTem.add(id_quer);
        id_quer.setText("Quer comprar");

        jLabel7.setText("Disponibilidade");

        id_botaoVoltar.setText("Voltar");
        id_botaoVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id_botaoVoltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(id_tem)
                                .addGap(70, 70, 70)
                                .addComponent(id_quer))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(id_edicao)
                                .addComponent(id_titulo)
                                .addComponent(id_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(id_editora)
                                .addComponent(id_autor)
                                .addComponent(id_serie, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(id_botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(id_botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(id_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(id_editora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(id_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(id_edicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(id_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_tem)
                    .addComponent(id_quer)
                    .addComponent(jLabel7))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void id_botaoSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id_botaoSalvarMouseClicked
        Livro livro = montaLivro();
        if(this.livro == null) {
            RepositorioLivro.adicionar(livro);
            JOptionPane.showMessageDialog(rootPane, "Livro adicionado com sucesso!");
        } else {
            livro.setId(this.livro.getId());
            RepositorioLivro.atualizar(livro);
            JOptionPane.showMessageDialog(rootPane, "Livro atualizado com sucesso!");
        }
        
        
        clearTela();
        voltarTela();
    }//GEN-LAST:event_id_botaoSalvarMouseClicked

    private Livro montaLivro() {
        boolean tem;
        if(id_tem.isSelected()) {
            tem = true;
        } else {
            tem = false;
        }
        String serie;
        if(id_serie.getText().isBlank()) {
            serie = id_titulo.getText();
        } else {
            serie = id_serie.getText();
        }
        Livro livro = new Livro(
                id_titulo.getText(),
                Integer.parseInt(id_ano.getText()),
                id_editora.getText(),
                id_autor.getText(),
                tem,
                id_edicao.getText(),
                serie
        );
        return livro;
    }
    
    private void recebeLivro() {
        id_titulo.setText(this.livro.getTitulo());
        id_ano.setText(this.livro.getAno() + "");
        id_editora.setText(this.livro.getEditora());
        id_autor.setText(this.livro.getAutor());
        id_edicao.setText(this.livro.getEdicao());
        id_serie.setText(this.livro.getSerie());
        if(this.livro.isTem()) {
            id_tem.setSelected(true);
        } else {
            id_quer.setSelected(true);
        }
    }
    
    private void clearTela() {
        id_titulo.setText("");
        id_ano.setText("");
        id_editora.setText("");
        id_autor.setText("");
        id_tem.setSelected(false);
        id_quer.setSelected(false);
        id_edicao.setText("");
        id_serie.setText("");
    }
    
    private void id_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_anoActionPerformed

    private void id_botaoVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id_botaoVoltarMouseClicked
        voltarTela();
    }//GEN-LAST:event_id_botaoVoltarMouseClicked

    private void voltarTela() {
        if(this.livro == null) {
            TelaPrincipal tela = new TelaPrincipal();
            tela.setVisible(true);
        }
        this.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdicionarLivro(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id_ano;
    private javax.swing.JTextField id_autor;
    private javax.swing.JButton id_botaoSalvar;
    private javax.swing.JButton id_botaoVoltar;
    private javax.swing.JTextField id_edicao;
    private javax.swing.JTextField id_editora;
    private javax.swing.ButtonGroup id_grupoTem;
    private javax.swing.JRadioButton id_quer;
    private javax.swing.JTextField id_serie;
    private javax.swing.JRadioButton id_tem;
    private javax.swing.JTextField id_titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
